### ISSUE TITLE
Fix incompatibilities with Visual Studio 2013

### ISSUE THREAD

**Issue by alexander-irrgang** [ViteFalcon/infectorpp#14]
1) constexpr is not supported in Visual Studio 2013
2) static_assert was not compatible with the current implementation of recursive trait_test (missing constexpr)
3) There is a bug with std::unique_ptr that prevents usage in VIsual Studio 2013

--> Try to fix all bugs or provide workaround

**Comment by ViteFalcon** [comment]
Thanks, Alex for bringing these up. The issues you've mentioned is already being addressed and/or is already notified in [README.md](https://github.com/ViteFalcon/infectorpp/blob/master/README.md)

1. `constexpr` is supported in the [**Visual Studio 2013 Update 4 CTP**](http://www.microsoft.com/en-us/download/details.aspx?id=41151) (as mentioned in the README.md). ***There is a caveat to that though***, which is that `constexpr` [isn't supported for member functions](http://blogs.msdn.com/b/vcblog/archive/2013/11/18/announcing-the-visual-c-compiler-november-2013-ctp.aspx) (Ctrl-F for 'constexpr'). Which is what causes the compiler issues. I already had a fix for this on my desktop, which I'm currently testing before pushing out. Essentially, I'm disabling that feature for Visual Studio versions less than 2015.
2. `static_assert` isn't compatible with the current implementation because `test_trait`, which is marked as `constexpr` is a member function.
3. We have a note in *README.md*, right towards the top that informs users about `std::unique_ptr` bug in Visual Studio 2013:

> **Note for VisualStudio users**: due to a VisualStudio bug, "std::unique_ptr" can't be used properly with Infectorpp. I hope they fix that soon, in the meanwhile, VS users could still inject quietly "std::shared_ptr".

While that's not the cleanest way to do things, there isn't much we can do other than making all instances to be stored and passed around as `std::shared_ptr`.

**Comment by alexander-irrgang** [comment]
I didn't grasp how Issues and Pull Requests were related on GitHub. I just added the link between this and my Pull Request :)

**Comment by ViteFalcon** [comment]
I just saw your latest pull-request. It seems like the files are in LF line-endings. Probably it was in CRLF line-endings before. I'll go ahead and pull that in. Thanks for the contribution! :+1: 

About how commits/pulls can be linked, Add the issue number like so `Fixed #14`, where 14 is this issues's number.
